[package]
edition = "2021"
name = "silent_slalom"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quicksilver = "0.3"
rand = "0.6"
