[package]
edition = "2021"
name = "working_with_data"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.10.0"
reqwest = "0.9.15"