[workspace]
members = ["ski", "silent_slalom", "gg_assets_slalom","assets_slalom"]


[package]
edition = "2021"
name = "creative-projects-rust-programmers"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
