[package]
edition = "2021"
name = "ml-utils"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.0.5"
itertools = "0.8.0"
ndarray = "0.12.1"
num-traits = "0.2.6"
serde = "1.0.89"
serde_derive = "1.0.89"
