[package]
edition = "2021"
name = "playerecs"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "~0.8.1"
legion = "=0.3.1"
serde = "=1.0.115"
ron = "=0.6.1"